services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - whatsapp-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: whatsapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsapp
    ports:
      - "5432:5432"
    networks:
      - whatsapp-network
    volumes:
      - db-data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - db
    networks:
      - whatsapp-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - whatsapp-network

  message-service:
    build:
      context: ./message-service
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - db
    networks:
      - whatsapp-network

  presence-service:
    build:
      context: ./presence-service
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  db-data: