sonar.projectKey=BenjaminLeclerc1_whatsapp-groupe4
sonar.organization=benjaminleclerc1

sonar.projectName=WhatsApp Groupe4
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/k6/**,**/frontend/**,**/infra/**,**/docs/**,**/*.pb.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8

sonar.branch.name=dev
